### ISSUE TITLE
Fix font style of "Our Advisors"

### ISSUE THREAD

**Issue by vaibhavchellani** [blockchainedindia/website#3]

**Comment by chinmayshah99** [comment]
Hey, @vaibhavchellani can you be more specific?

**Comment by vaibhavchellani** [comment]
hey @chinmayshah99 sorry for not being specific before , but i was just going through the site and there is a part where you have given the pics and links of advisors , the font style of "Our Advisors" is different than all other headings , right ?

**Comment by vaibhavchellani** [comment]
<img width="1440" alt="screen shot 2018-05-29 at 12 29 31 am" src="https://user-images.githubusercontent.com/19390504/40626626-71833bb0-62d7-11e8-8bdc-f8e37dbfe27e.png">
see the difference in headings , i hope this clears it up

**Comment by anistark** [comment]
@vaibhavchellani Thanks for the look-out!
