### ISSUE TITLE
Subscribe button not working

### ISSUE THREAD

**Issue by anistark** [blockchainedindia/website#37]
### Expected behavior and actual behavior.
On clicking on subscribe, the subscription info should trigger sendy form.

### Steps to reproduce the problem.
Click on Subscribe at the bottom of the page.

### Specifications like the version of the project, operating system, or hardware.
Web. cross-platform support.

**Comment by nafees87n** [comment]
I want to work on this

**Comment by anistark** [comment]
Sure. Assigning to you.

**Comment by nafees87n** [comment]
> Sure. Assigning to you.

I have made a pull request

**Comment by anistark** [comment]
Thanks @nafees87n. Fixed now.
